apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall-agent.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "heimdall-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https-metrics" "http-metrics" .Values.metrics.secure }}
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
