package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// SchemaID is the published location of the schema, for editor integrations:
//
//	# yaml-language-server: $schema=<SchemaID>
const SchemaID = "https://raw.githubusercontent.com/heimdall-dev/heimdall/main/schema/heimdall.schema.json"

// JSONSchema returns the JSON Schema (draft-07, the most widely supported
// draft) for heimdall.yaml. It is generated by reflecting over the Go types,
// and its patterns and enums reuse the validator's own regular expressions and
// version lists, so the two cannot drift apart.
//
// The schema is an editor aid: it catches typos, wrong types and simple value
// errors as you type. Cross-field rules (one primary service, dependency
// cycles, tenant policy, quotas) are enforced by [Load] only, so a file can
// match the schema and still be rejected. Files that Load accepts always match
// the schema.
func JSONSchema() ([]byte, error) {
	g := &schemaGen{defs: map[string]any{}}
	root := g.object(reflect.TypeFor[Config]())
	root["$schema"] = "http://json-schema.org/draft-07/schema#"
	root["$id"] = SchemaID
	root["title"] = "heimdall.yaml"
	root["definitions"] = g.defs
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode schema: %w", err)
	}
	return append(out, '\n'), nil
}

type schemaGen struct {
	defs map[string]any
}

var durationType = reflect.TypeFor[Duration]()

// Value patterns, in the subset of regular-expression syntax shared by Go
// (RE2) and ECMA-262, which JSON Schema uses.
const (
	// \u00b5 is the micro sign: Go also accepts "\u00b5s" for "us".
	// Escaped so this file stays ASCII.
	durationPattern = "^([0-9]+d|([0-9]+(\\.[0-9]+)?(ns|us|\u00b5s|ms|s|m|h))+)$"
	cpuPattern      = `^([0-9]+m|[0-9]*\.?[0-9]+)$`
	memoryPattern   = `^[0-9]+(Mi|Gi)$`
)

func (g *schemaGen) schemaFor(t reflect.Type) map[string]any {
	if t == durationType {
		return map[string]any{"type": "string", "pattern": durationPattern}
	}
	switch t.Kind() {
	case reflect.Pointer:
		return g.schemaFor(t.Elem())
	case reflect.Struct:
		if _, ok := g.defs[t.Name()]; !ok {
			g.defs[t.Name()] = nil // reserve the name before recursing
			g.defs[t.Name()] = g.object(t)
		}
		return map[string]any{"$ref": "#/definitions/" + t.Name()}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Int, reflect.Int64:
		return map[string]any{"type": "integer"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": g.schemaFor(t.Elem())}
	case reflect.Slice:
		return map[string]any{"type": "array", "items": g.schemaFor(t.Elem())}
	}
	panic(fmt.Sprintf("config: no JSON Schema mapping for %s", t))
}

func (g *schemaGen) object(t reflect.Type) map[string]any {
	props := map[string]any{}
	for _, name := range yamlFields(t) {
		f, _ := fieldByYAMLName(t, name)
		key := t.Name() + "." + name
		s := g.schemaFor(f.Type)
		if _, isRef := s["$ref"]; isRef {
			// draft-07 ignores keywords next to $ref; wrap to keep the description.
			s = map[string]any{"allOf": []any{s}}
		}
		for k, v := range fieldSchemas[key] {
			s[k] = v
		}
		s["description"] = fieldDocs[key]
		props[name] = s
	}
	obj := map[string]any{
		"type":                 "object",
		"description":          typeDocs[t.Name()],
		"properties":           props,
		"additionalProperties": false,
	}
	for k, v := range typeSchemas[t.Name()] {
		obj[k] = v
	}
	return obj
}

func fieldByYAMLName(t reflect.Type, name string) (reflect.StructField, bool) {
	for i := range t.NumField() {
		if tag, _, _ := strings.Cut(t.Field(i).Tag.Get("yaml"), ","); tag == name {
			return t.Field(i), true
		}
	}
	return reflect.StructField{}, false
}

func pattern(p string) map[string]any { return map[string]any{"type": "string", "pattern": p} }

// scalar matches YAML scalars that decode into a Go string: `PORT: 8080` and
// `DEBUG: true` are as valid as quoted values.
var scalar = map[string]any{"type": []any{"string", "number", "boolean"}}

// versionEnum accepts `version: "16"` and `version: 16`; both decode to "16".
func versionEnum(versions []string) map[string]any {
	enum := make([]any, 0, 2*len(versions))
	for _, v := range versions {
		enum = append(enum, v)
	}
	for _, v := range versions {
		enum = append(enum, json.Number(v))
	}
	return map[string]any{"type": []any{"string", "number"}, "enum": enum}
}

var oneSource = []any{
	map[string]any{"required": []any{"build"}},
	map[string]any{"required": []any{"image"}},
}

// typeSchemas adds object-level rules to a definition.
var typeSchemas = map[string]map[string]any{
	"Config":     {"required": []any{"version", "services"}},
	"Service":    {"required": []any{"port"}, "oneOf": oneSource},
	"Worker":     {"required": []any{"command"}, "oneOf": oneSource},
	"Migrations": {"required": []any{"service", "command"}},
	"SmokeTest":  {"required": []any{"name", "command"}},
	"Resources": {"dependencies": map[string]any{
		"size": map[string]any{"properties": map[string]any{"cpu": false, "memory": false, "requests": false}},
	}},
}

// fieldSchemas refines reflected field schemas, keyed by "Type.field".
var fieldSchemas = map[string]map[string]any{
	"Config.version":     {"const": CurrentVersion},
	"Config.services":    {"minProperties": 1, "propertyNames": pattern(nameRE.String())},
	"Config.workers":     {"propertyNames": pattern(nameRE.String())},
	"Config.smokeTests":  {"maxItems": maxSmokeTests},
	"Build.args":         {"propertyNames": pattern(envKeyRE.String()), "additionalProperties": scalar},
	"Health.path":        {"pattern": `^/\S*$`},
	"Resources.size":     {"enum": []any{SizeSmall, SizeMedium, SizeLarge}},
	"Resources.cpu":      {"pattern": cpuPattern},
	"Resources.memory":   {"pattern": memoryPattern},
	"Requests.cpu":       {"pattern": cpuPattern},
	"Requests.memory":    {"pattern": memoryPattern},
	"Service.image":      {"pattern": imageRE.String()},
	"Service.port":       {"minimum": 1, "maximum": 65535},
	"Service.env":        {"propertyNames": pattern(envKeyRE.String()), "additionalProperties": scalar},
	"Service.secrets":    {"items": pattern(secretRE.String()), "uniqueItems": true},
	"Worker.image":       {"pattern": imageRE.String()},
	"Worker.env":         {"propertyNames": pattern(envKeyRE.String()), "additionalProperties": scalar},
	"Worker.secrets":     {"items": pattern(secretRE.String()), "uniqueItems": true},
	"Worker.replicas":    {"minimum": 0, "maximum": MaxWorkerReplicas},
	"Postgres.version":   versionEnum(supportedPostgres),
	"Postgres.storage":   {"pattern": memoryPattern},
	"Postgres.seed":      {"pattern": `\.[sS][qQ][lL]$`},
	"Redis.version":      versionEnum(supportedRedis),
	"RabbitMQ.version":   versionEnum(supportedRabbitMQ),
	"SmokeTest.name":     {"pattern": nameRE.String()},
	"Preview.visibility": {"enum": []any{VisibilityPrivate, VisibilityOrg, VisibilityPublic}},
}

var typeDocs = map[string]string{
	"Config":       "Heimdall preview environment configuration (heimdall.yaml).",
	"Build":        "How to build the image from the repository.",
	"Health":       "HTTP readiness probe.",
	"Resources":    "Container resources: a size preset, or explicit limits with optional requests.",
	"Requests":     "Scheduler reservations.",
	"Service":      "A long-running workload that listens on a port.",
	"Worker":       "A long-running workload without a port (queue consumer, loop).",
	"Dependencies": "Managed backing services. Presence enables one; use {} for defaults.",
	"Postgres":     "Per-environment PostgreSQL.",
	"Redis":        "Per-environment Redis.",
	"RabbitMQ":     "Per-environment RabbitMQ.",
	"Migrations":   "Schema migrations, run as a Job before services start.",
	"SmokeTest":    "A command run inside the environment once it is ready.",
	"Preview":      "Environment lifecycle and access.",
}

const (
	docBuild     = "Build the image from the repository. Exactly one of build or image is required."
	docImage     = "Prebuilt image reference, from a registry your organisation allows."
	docEnv       = "Plain, non-secret environment variables. HEIMDALL_* and injected names (PORT, DATABASE_URL, REDIS_URL, AMQP_URL) are reserved."
	docSecrets   = "Names of secrets stored in Heimdall, injected as environment variables (UPPER_SNAKE_CASE)."
	docResources = "Container resources. Default: medium for services, small for workers."
)

var fieldDocs = map[string]string{
	"Config.version":      "Schema version. Must be 1.",
	"Config.services":     "Long-running network workloads, keyed by name. At least one is required.",
	"Config.dependencies": "Managed backing services: postgres, redis, rabbitmq.",
	"Config.workers":      "Long-running workloads without a port, keyed by name.",
	"Config.migrations":   "Schema migrations, run against the baseline database before services start.",
	"Config.smokeTests":   "Commands run inside the environment once everything is ready (at most 10).",
	"Config.preview":      "Lifecycle and access.",

	"Build.context":    `Docker build context, relative to the repository root. Default: ".".`,
	"Build.dockerfile": "Dockerfile path, relative to the context. Default: Dockerfile.",
	"Build.args":       "Build arguments. Never put secrets here: they end up in the image history.",

	"Health.path":         "HTTP path probed for readiness, for example /health.",
	"Health.initialDelay": "Wait before the first probe; at most 300s. Default: 5s.",

	"Resources.size":     "Preset limits: small (250m, 256Mi), medium (500m, 512Mi) or large (1 CPU, 2Gi; needs approval). Not combinable with cpu, memory or requests.",
	"Resources.cpu":      `CPU limit: cores ("1", "0.5") or millicores ("250m").`,
	"Resources.memory":   `Memory limit in binary units, for example "512Mi" or "1Gi".`,
	"Resources.requests": "Scheduler reservations. Default: CPU 20% of the limit; memory 50% of the limit, at least 64Mi.",
	"Requests.cpu":       "CPU request; at most the CPU limit.",
	"Requests.memory":    "Memory request; at most the memory limit, and at least half of it by default policy.",

	"Service.build":     docBuild,
	"Service.image":     docImage,
	"Service.port":      "Port the process listens on; also injected as PORT.",
	"Service.public":    "Expose the service through a preview URL.",
	"Service.primary":   "Owns the bare preview URL. Required when several services are public.",
	"Service.env":       docEnv,
	"Service.secrets":   docSecrets,
	"Service.health":    "HTTP readiness probe. Without it, a TCP probe on the port is used.",
	"Service.resources": docResources,
	"Service.dependsOn": "Services and enabled dependencies that must be ready first.",

	"Worker.build":     docBuild,
	"Worker.image":     docImage,
	"Worker.command":   "Command, run through sh -c.",
	"Worker.env":       docEnv,
	"Worker.secrets":   docSecrets,
	"Worker.replicas":  "Number of replicas, 1-5. Default: 1.",
	"Worker.resources": docResources,
	"Worker.dependsOn": "Services and enabled dependencies that must be ready first.",

	"Dependencies.postgres": "PostgreSQL, one per environment.",
	"Dependencies.redis":    "Redis, one per environment.",
	"Dependencies.rabbitmq": "RabbitMQ, one per environment.",

	"Postgres.version": `Major version. Default: "16".`,
	"Postgres.storage": `Volume size, for example "2Gi". Default: 1Gi.`,
	"Postgres.seed":    "A .sql file, relative to the repository root, loaded after migrations. Reset restores this baseline.",
	"Redis.version":    `Major version. Default: "7".`,
	"RabbitMQ.version": `Version. Default: "3.13".`,

	"Migrations.service": "Service whose image contains the migration tool.",
	"Migrations.command": "Migration command, run through sh -c.",
	"Migrations.timeout": "At most 30m. Default: 5m.",

	"SmokeTest.name":    "Short name for the PR report.",
	"SmokeTest.command": "Command run through sh -c in a toolbox image with curl; service names resolve as hostnames.",
	"SmokeTest.timeout": "At most 10m. Default: 2m.",

	"Preview.ttl":        "How long the environment lives, for example 48h or 2d. Default: 48h.",
	"Preview.sleepAfter": "Scale to zero after this much inactivity: at least 10m, and shorter than ttl.",
	"Preview.visibility": "Who may open the preview: private (default), org or public.",
}
