// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndSwapStatus = `-- name: CompareAndSwapStatus :execrows
UPDATE heimdall.environments SET phase = $1, status = $2, version = version + 1, updated_at = now() WHERE id = $3 AND version = $4 AND generation = $5
`

type CompareAndSwapStatusParams struct {
	Phase      string `json:"phase"`
	Status     []byte `json:"status"`
	ID         string `json:"id"`
	Version    int64  `json:"version"`
	Generation int64  `json:"generation"`
}

func (q *Queries) CompareAndSwapStatus(ctx context.Context, arg CompareAndSwapStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapStatus,
		arg.Phase,
		arg.Status,
		arg.ID,
		arg.Version,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id,tenant_id::text,repository_id::text,cluster_id::text,name,pull_request,owner,commit_sha,version,generation,reset_nonce,desired_state,phase,build_state,spec,status,expires_at,created_at,updated_at FROM heimdall.environments WHERE id = $1
`

type GetEnvironmentRow struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	RepositoryID string             `json:"repository_id"`
	ClusterID    string             `json:"cluster_id"`
	Name         string             `json:"name"`
	PullRequest  int64              `json:"pull_request"`
	Owner        string             `json:"owner"`
	CommitSha    string             `json:"commit_sha"`
	Version      int64              `json:"version"`
	Generation   int64              `json:"generation"`
	ResetNonce   int64              `json:"reset_nonce"`
	DesiredState string             `json:"desired_state"`
	Phase        string             `json:"phase"`
	BuildState   string             `json:"build_state"`
	Spec         []byte             `json:"spec"`
	Status       []byte             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEnvironment(ctx context.Context, id string) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepositoryID,
		&i.ClusterID,
		&i.Name,
		&i.PullRequest,
		&i.Owner,
		&i.CommitSha,
		&i.Version,
		&i.Generation,
		&i.ResetNonce,
		&i.DesiredState,
		&i.Phase,
		&i.BuildState,
		&i.Spec,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT policy FROM heimdall.tenant_policy WHERE tenant_id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, tenantID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPolicy, tenantID)
	var policy []byte
	err := row.Scan(&policy)
	return policy, err
}

const getTenant = `-- name: GetTenant :one
SELECT id::text, slug, name FROM heimdall.tenants WHERE id = $1
`

type GetTenantRow struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO heimdall.audit_log(tenant_id,actor_id,action,resource,metadata) VALUES($1,$2,$3,$4,$5)
`

type InsertAuditParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ActorID  string      `json:"actor_id"`
	Action   string      `json:"action"`
	Resource string      `json:"resource"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.Metadata,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO heimdall.events(tenant_id,environment_id,generation,kind,payload,source_event_id) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertEventParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID string      `json:"environment_id"`
	Generation    int64       `json:"generation"`
	Kind          string      `json:"kind"`
	Payload       []byte      `json:"payload"`
	SourceEventID pgtype.Text `json:"source_event_id"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Generation,
		arg.Kind,
		arg.Payload,
		arg.SourceEventID,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO heimdall.outbox(tenant_id,environment_id,generation,kind,payload) VALUES($1,$2,$3,$4,$5)
`

type InsertOutboxParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.Text `json:"environment_id"`
	Generation    int64       `json:"generation"`
	Kind          string      `json:"kind"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Generation,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const lockEnvironment = `-- name: LockEnvironment :one
SELECT id,tenant_id::text,repository_id::text,cluster_id::text,name,pull_request,owner,commit_sha,version,generation,reset_nonce,desired_state,phase,build_state,spec,status,expires_at,created_at,updated_at FROM heimdall.environments WHERE id = $1 FOR UPDATE
`

type LockEnvironmentRow struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	RepositoryID string             `json:"repository_id"`
	ClusterID    string             `json:"cluster_id"`
	Name         string             `json:"name"`
	PullRequest  int64              `json:"pull_request"`
	Owner        string             `json:"owner"`
	CommitSha    string             `json:"commit_sha"`
	Version      int64              `json:"version"`
	Generation   int64              `json:"generation"`
	ResetNonce   int64              `json:"reset_nonce"`
	DesiredState string             `json:"desired_state"`
	Phase        string             `json:"phase"`
	BuildState   string             `json:"build_state"`
	Spec         []byte             `json:"spec"`
	Status       []byte             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockEnvironment(ctx context.Context, id string) (LockEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, lockEnvironment, id)
	var i LockEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepositoryID,
		&i.ClusterID,
		&i.Name,
		&i.PullRequest,
		&i.Owner,
		&i.CommitSha,
		&i.Version,
		&i.Generation,
		&i.ResetNonce,
		&i.DesiredState,
		&i.Phase,
		&i.BuildState,
		&i.Spec,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lookupCredential = `-- name: LookupCredential :one
SELECT id::text,actor_id,COALESCE(cluster_id::text,'') AS cluster_id,role,kind,token_hash,expires_at,revoked_at FROM heimdall.credentials WHERE id = $1
`

type LookupCredentialRow struct {
	ID        string             `json:"id"`
	ActorID   string             `json:"actor_id"`
	ClusterID interface{}        `json:"cluster_id"`
	Role      string             `json:"role"`
	Kind      string             `json:"kind"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) LookupCredential(ctx context.Context, id pgtype.UUID) (LookupCredentialRow, error) {
	row := q.db.QueryRow(ctx, lookupCredential, id)
	var i LookupCredentialRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ClusterID,
		&i.Role,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const timeline = `-- name: Timeline :many
SELECT id,environment_id,generation,kind,payload,created_at FROM heimdall.events WHERE environment_id = $1 AND id > $2 ORDER BY id LIMIT $3
`

type TimelineParams struct {
	EnvironmentID string `json:"environment_id"`
	ID            int64  `json:"id"`
	Limit         int32  `json:"limit"`
}

type TimelineRow struct {
	ID            int64              `json:"id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	Kind          string             `json:"kind"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) Timeline(ctx context.Context, arg TimelineParams) ([]TimelineRow, error) {
	rows, err := q.db.Query(ctx, timeline, arg.EnvironmentID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineRow{}
	for rows.Next() {
		var i TimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Generation,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
