// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HeimdallAuditLog struct {
	ID        int64              `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ActorID   string             `json:"actor_id"`
	Action    string             `json:"action"`
	Resource  string             `json:"resource"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HeimdallBuildReceipt struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	RepositoryID  pgtype.UUID        `json:"repository_id"`
	PullRequest   int64              `json:"pull_request"`
	RunID         string             `json:"run_id"`
	RunAttempt    int64              `json:"run_attempt"`
	RequestHash   []byte             `json:"request_hash"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallCluster struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	AgentVersion  string             `json:"agent_version"`
	Tier          int32              `json:"tier"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallCredential struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ActorID           string             `json:"actor_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Role              string             `json:"role"`
	Kind              string             `json:"kind"`
	TokenHash         []byte             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RotationNonceHash []byte             `json:"rotation_nonce_hash"`
	SuccessorAccess   pgtype.UUID        `json:"successor_access"`
	SuccessorRefresh  pgtype.UUID        `json:"successor_refresh"`
	ReplayUntil       pgtype.Timestamptz `json:"replay_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type HeimdallDataAttestation struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	PullRequest  int64              `json:"pull_request"`
	ConfigSha256 string             `json:"config_sha256"`
	SeedSha256   string             `json:"seed_sha256"`
	ApprovedBy   string             `json:"approved_by"`
	Reason       string             `json:"reason"`
	Sanitised    bool               `json:"sanitised"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type HeimdallDeployment struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	CommitSha     string             `json:"commit_sha"`
	Spec          []byte             `json:"spec"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallDiagnosis struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	Code          string             `json:"code"`
	Summary       string             `json:"summary"`
	Suggestion    string             `json:"suggestion"`
	Evidence      []byte             `json:"evidence"`
	Subject       string             `json:"subject"`
	Stage         string             `json:"stage"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallEnvironment struct {
	ID           string             `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	ClusterID    pgtype.UUID        `json:"cluster_id"`
	Name         string             `json:"name"`
	PullRequest  int64              `json:"pull_request"`
	Owner        string             `json:"owner"`
	CommitSha    string             `json:"commit_sha"`
	Version      int64              `json:"version"`
	Generation   int64              `json:"generation"`
	ResetNonce   int64              `json:"reset_nonce"`
	DesiredState string             `json:"desired_state"`
	Phase        string             `json:"phase"`
	BuildState   string             `json:"build_state"`
	Spec         []byte             `json:"spec"`
	Status       []byte             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HeimdallEvent struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	Kind          string             `json:"kind"`
	Payload       []byte             `json:"payload"`
	SourceEventID pgtype.Text        `json:"source_event_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallGithubDeliveryState struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	CommentID     int64              `json:"comment_id"`
	CheckID       int64              `json:"check_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type HeimdallIdempotencyKey struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ActorID     string             `json:"actor_id"`
	Key         string             `json:"key"`
	RequestHash []byte             `json:"request_hash"`
	Response    []byte             `json:"response"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type HeimdallInstallation struct {
	ID        int64              `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Account   string             `json:"account"`
	Suspended bool               `json:"suspended"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HeimdallInstallationRoute struct {
	InstallationID int64       `json:"installation_id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
}

type HeimdallOutbox struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	Generation    int64              `json:"generation"`
	Kind          string             `json:"kind"`
	Payload       []byte             `json:"payload"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LeaseToken    pgtype.Text        `json:"lease_token"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
	Worker        pgtype.Text        `json:"worker"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type HeimdallPullRequest struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	RepositoryID   pgtype.UUID        `json:"repository_id"`
	Number         int64              `json:"number"`
	HeadSha        string             `json:"head_sha"`
	BaseSha        string             `json:"base_sha"`
	State          string             `json:"state"`
	IsFork         bool               `json:"is_fork"`
	NeedsApproval  bool               `json:"needs_approval"`
	ApprovedSha    string             `json:"approved_sha"`
	ConfigDigest   string             `json:"config_digest"`
	BaselineDigest string             `json:"baseline_digest"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	Version        int64              `json:"version"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TraceParent    string             `json:"trace_parent"`
}

type HeimdallQuota struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	MaxEnvironments int32       `json:"max_environments"`
	MaxCpuMilli     int32       `json:"max_cpu_milli"`
	MaxMemoryMi     int32       `json:"max_memory_mi"`
	MaxStorageMi    int32       `json:"max_storage_mi"`
}

type HeimdallRepository struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	GithubID           int64              `json:"github_id"`
	InstallationID     int64              `json:"installation_id"`
	ClusterID          pgtype.UUID        `json:"cluster_id"`
	FullName           string             `json:"full_name"`
	DefaultBranch      string             `json:"default_branch"`
	Enabled            bool               `json:"enabled"`
	TrustedWorkflowRef string             `json:"trusted_workflow_ref"`
	TrustedWorkflowSha string             `json:"trusted_workflow_sha"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type HeimdallSmokeRun struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	Generation    int64              `json:"generation"`
	Name          string             `json:"name"`
	Passed        bool               `json:"passed"`
	DurationMs    int64              `json:"duration_ms"`
	Summary       string             `json:"summary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HeimdallTenant struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HeimdallTenantPolicy struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Policy          []byte             `json:"policy"`
	Version         int64              `json:"version"`
	DesiredRevision int64              `json:"desired_revision"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type HeimdallTenantRoute struct {
	TenantID pgtype.UUID `json:"tenant_id"`
}

type HeimdallUsageSample struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EnvironmentID string             `json:"environment_id"`
	CpuMilli      int32              `json:"cpu_milli"`
	MemoryMi      int32              `json:"memory_mi"`
	StorageMi     int32              `json:"storage_mi"`
	SampledAt     pgtype.Timestamptz `json:"sampled_at"`
}

type HeimdallWebhookDelivery struct {
	DeliveryID   string             `json:"delivery_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Event        string             `json:"event"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	PullRequest  int64              `json:"pull_request"`
	Payload      []byte             `json:"payload"`
	PayloadHash  string             `json:"payload_hash"`
	State        string             `json:"state"`
	Attempts     int32              `json:"attempts"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	LeaseToken   pgtype.Text        `json:"lease_token"`
	LeaseUntil   pgtype.Timestamptz `json:"lease_until"`
	Worker       pgtype.Text        `json:"worker"`
	LastError    string             `json:"last_error"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}
